### ISSUE TITLE
question and IndexError: list index out of range

### ISSUE THREAD

**Issue by Ivanbh214** [rvolden/C3POa#6]
Hello, 

I would like to use the pipeline for analysys very short amplicons (from 250 to 500 bp) . Do you think that could be possible with this pipeline?

I've tried to used, I installed all the requeriments and I'm using Python(3.6) and Numphy in a enviroment. For the rest of the softwares I've installed with setup.py(the last version), go ( the install process was ok) and blat,  I had some problems whit the path for it but finally I made it.  
When I run this command line for the preprocessing:

(phy3)python C3POa_preprocessing.py -i BC26.fastq -o /home/ivan/C3POa  -q 7 -l 160 -s Adapters_1d2.fasta -c configf.txt

I obtained:
raceback (most recent call last):
  File "C3POa_preprocessing.py", line 63, in <module>
    progs = configReader(args['config'])
  File "C3POa_preprocessing.py", line 41, in configReader
    progs[line[0]] = line[1]
IndexError: list index out of range

the configf.file(I've copied your example)
# Order doesn't matter
# If you use the config file, you should provide paths to all of the programs
# You need to include all of the example programs
# Use tabs to separate the program name from the path

poa	/home/ivan/C3POa/bio-pipeline/poaV2/poa
racon	/home/ivan/C3POa/racon/bin/racon
water	/home/ivan/C3POa/EMBOSS-6.6.0/emboss/water
minimap2 /home/ivan/C3POa/minimap2/minimap2
consensus /home/ivan/C3POa/consensus.py
racon	/home/ivan/C3POa/racon/bin/racon
blat    /home/ivan/blatSrc

I changed /home/ivan/blatSrc for blat but the result is the same. 
What do you think that could be the problem?the blat installation?

Thank you very much

**Comment by rvolden** [comment]
It looks like your config file isn't tab delimited, but is delimited with a space instead. I think changing the spaces to tabs will fix your issue.

**Comment by Ivanbh214** [comment]
Thank you very much for your answer, I changed the configf.txt file.
configf.txt that I've used.
[configf.txt](https://github.com/rvolden/C3POa/files/2958070/configf.txt)

> #configf 
poa/home/ivan/C3POa/bio-pipeline/poaV2/poa
racon/home/ivan/C3POa/racon/bin/racon
water/home/ivan/C3POa/EMBOSS-6.6.0/emboss/water
minimap2/home/ivan/C3POa/minimap2/minimap2
consensus/home/ivan/C3POa/consensus.py
racon/home/ivan/C3POa/racon/bin/racon
blat/home/ivan/blatSrc

The same result:
~/C3POa$ python C3POa_preprocessing.py -i BC26.fastq -o /home/ivan/C3POa  -q 7 -l 160 -s Adapters_1d2.fasta -c configf.txt


Traceback (most recent call last):
  File "C3POa_preprocessing.py", line 63, in <module>
    progs = configReader(args['config'])
  File "C3POa_preprocessing.py", line 41, in configReader
    progs[line[0]] = line[1]
IndexError: list index out of range

Thank you

**Comment by rvolden** [comment]
[configf.txt](https://github.com/rvolden/C3POa/files/2958280/configf.txt)
I have added tabs to your file, this should work

**Comment by Ivanbh214** [comment]
Thank you very much for the file.
I checked the file and worked, but I think that I have problems with the blat installation.

~/C3POa$ python C3POa_preprocessing.py -i BC26.fastq -o /home/ivan/C3POa  -q 7 -l 160 -s Adapters_1d2.fasta -c configf.txt
Reading and filtering fastq file
Running BLAT to find splint locations (This can take hours)
sh: 1: /home/ivan/blatSrc: Permission denied
Parsing BLAT output
Traceback (most recent call last):
  File "C3POa_preprocessing.py", line 214, in <module>
    main()
  File "C3POa_preprocessing.py", line 209, in main
    adapter_dict = parse_blat(output_path)
  File "C3POa_preprocessing.py", line 135, in parse_blat
    for line in open(alignment_file):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ivan/C3POa//Splint_to_read_alignments.psl'

It could be a problem with the installation, I think,I'll try to solve it and after that I closed the issue.

Thank you very much

**Comment by rvolden** [comment]
Check your blat file to make sure it's executable
